FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y --no-install-recommends locales python3 python3-pip tzdata

RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV TZ=Europe/Kiev

ARG WORKDIR=/checkbox451_bot

ARG TELEGRAM_BOT_ADMIN
ARG DB_DIR=$WORKDIR

ARG TELEGRAM_BOT_TOKEN

ARG CHECKBOX_LOGIN
ARG CHECKBOX_PASSWORD
ARG CHECKBOX_LICENSE
ARG CHECKBOX_API_URL

ARG PRINTER_CONFIG
ARG PRINT_WIDTH
ARG PRINT_BOTTOM_MARGIN
ARG PRINT_LOGO_PATH
ARG PRINT_LOGO_IMPL

ARG GOOGLE_APPLICATION_CREDENTIALS
ARG GOOGLE_SPREADSHEET_KEY
ARG GOOGLE_WORKSHEET_TITLE

ARG SHIFT_CLOSE_TIME

ENV TELEGRAM_BOT_ADMIN=$TELEGRAM_BOT_ADMIN
ENV DB_DIR=$DB_DIR

ENV TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN

ENV CHECKBOX_LOGIN=$CHECKBOX_LOGIN
ENV CHECKBOX_PASSWORD=$CHECKBOX_PASSWORD
ENV CHECKBOX_LICENSE=$CHECKBOX_LICENSE
ENV CHECKBOX_API_URL=$CHECKBOX_API_URL

ENV PRINTER_CONFIG=$PRINTER_CONFIG
ENV PRINT_WIDTH=$PRINT_WIDTH
ENV PRINT_BOTTOM_MARGIN=$PRINT_BOTTOM_MARGIN
ENV PRINT_LOGO_PATH=$PRINT_LOGO_PATH
ENV PRINT_LOGO_IMPL=$PRINT_LOGO_IMPL

ENV GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
ENV GOOGLE_SPREADSHEET_KEY=$GOOGLE_SPREADSHEET_KEY
ENV GOOGLE_WORKSHEET_TITLE=$GOOGLE_WORKSHEET_TITLE

ENV SHIFT_CLOSE_TIME=$SHIFT_CLOSE_TIME

WORKDIR $WORKDIR
COPY . $WORKDIR
RUN pip3 install .

CMD python3 -m checkbox451_bot
