version: "3.2"

services:
  bot:
    build:
      context: .
    volumes:
      - type: bind
        source: ${PWD}
        target: /checkbox451_bot

    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: 10m
