[build-system]
requires = ["setuptools", "setuptools-declarative-requirements", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[tool.isort]
line_length = 79
profile = "black"
