AUTH_REQUIRED = "Потрібна авторизація"
AUTHENTICATE = "Авторизуватися"
ADMIN_APPROVE = "Адміністратор має підтвердити"
START = "Вітаю!"
CREATE_RECEIPT = "Створити чек"
PRINT = "Друкувати"
PRINTING = "Друкую…"
SELECT_GOOD = "Оберіть позицію"
