AUTH_REQUIRED = "Потрібна авторизація"
AUTHENTICATE = "Авторизуватися"
DENIED = "Відмова"
START = "Вітаю!"
CREATE_RECEIPT = "Створити чек"
PRINT = "Друкувати"
PRINTING = "Друкую…"
SELECT_GOOD = "Оберіть позицію"
