AUTH_REQUIRED = "Потрібна авторизація"
AUTHENTICATE = "Авторизуватися"
DENIED = "Відмова"
ACTION = "Оберіть дію"
CREATE_RECEIPT = "Створити чек"
PRINT = "Друк"
PRINTING = "Друкую…"
SELECT_GOOD = "Оберіть позицію"
